apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80

#M = Milicor = 
#1000M = 1vCPU
#vCPU = Unidado quando contratamos qualquer CPU em um cloud provider
